name: Run WEB Tests
run-name: On Push - Web Tests Run
on: [push]

jobs: 
  web-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
    
      - name: Install Node.js
        uses: actions/setup-node@v3
        with: 
         node-version: '19.1'
      
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init

      - name:  Run RF WEB tests
        run: |
          robot -d./results -v HEADLESS:true -v BROWSER:chromium tests
      
      - name: Upload Test Results 
        if: always()      #if porque precisa executar sempre, do contrário ele só executa os próximso passos se o anterior deu certo
        uses: actions/upload-artifact@v3
        with: 
          name: results-chromium
          path: ./results
          if-no-files-found: ignore     #se não encontrar os arquivos, ignore
          retention-days: 2             #só segura por 2 dias, depois exclui da memória do github